import {
  BedIcon,
  BellIcon,
  BikeIcon,
  BoatIcon,
  CarIcon,
  CheckIcon,
  CompassIcon,
  GlassIcon,
  LeafIcon,
  LockIcon,
  MoonIcon,
  MountainIcon,
  PalmIcon,
  PlaneIcon,
  PoolIcon,
  SnowflakeIcon,
  SunIcon,
  TentIcon,
  UsersIcon,
  UtensilsIcon,
  WaterIcon,
  WifiIcon,
} from "@/components/ui/icons";

/** One icon per facility or room feature, shared by stay and room pages. */
const ICONS: Record<string, typeof BedIcon> = {
  "24-hour front desk": BellIcon,
  "Free Wi-Fi": WifiIcon,
  "Free Internet": WifiIcon,
  Restaurant: UtensilsIcon,
  Bar: GlassIcon,
  Minibar: GlassIcon,
  "Swimming pool": PoolIcon,
  "Plunge pool": PoolIcon,
  "Air-conditioning": SnowflakeIcon,
  "Fan & air-conditioning": SnowflakeIcon,
  Fan: SnowflakeIcon,
  "Airport transfer": PlaneIcon,
  Spa: LeafIcon,
  Parking: CarIcon,
  Beachfront: PalmIcon,
  Hammock: PalmIcon,
  "Boat transfers": BoatIcon,
  Kayaks: BoatIcon,
  "Snorkelling gear": WaterIcon,
  "Private bathroom": WaterIcon,
  "Shared bathroom": WaterIcon,
  "Rain shower": WaterIcon,
  "Hot shower": WaterIcon,
  "Outdoor shower": WaterIcon,
  Bathtub: WaterIcon,
  Bicycles: BikeIcon,
  "Home-cooked meals": UtensilsIcon,
  "Meals included": UtensilsIcon,
  Kitchenette: UtensilsIcon,
  "Mosquito net": MoonIcon,
  "Mosquito nets": MoonIcon,
  "Local guide": CompassIcon,
  "Guided treks": MountainIcon,
  "Walking trails": MountainIcon,
  "Solar power": SunIcon,
  Campfire: SunIcon,
  "Private terrace": SunIcon,
  Balcony: SunIcon,
  "Tents provided": TentIcon,
  "Camping ground": TentIcon,
  "Separate living area": UsersIcon,
  "Two bedrooms": BedIcon,
  Safe: LockIcon,
};

/** The icon for a facility or feature; anything unlisted gets a tick. */
export function amenityIcon(name: string) {
  return ICONS[name] ?? CheckIcon;
}
